### ISSUE TITLE
Message: Failed to complete #create action: [Names can't be blank]

### ISSUE THREAD

**Issue by skidmarq** [digitalocean/droplet_kit#76]
I just pulled this down to try for the first time, so the problem I've hit could absolutely be on my end, but I [kept getting the message](https://gist.github.com/skidmarq/fd4625dbfbc8cf92d670) `Message: Failed to complete #create action: [Names can't be blank]` when I'd try to create a droplet using the **kitchen-digitalocean** driver. I found I'm able to create without error if I comment out line 30 of **lib/droplet_kit/mappings/droplet_mapping.rb** which was added just a few days ago in commit 284d0e1.  **name** appears to be automagically generated with the driver, but I don't see where it's doing anything for **names**.  Is this something I'm just overlooking in my **.kitchen.yml**, or just that **kitchen-digitalocean** hasn't caught up with the latest updates here?  (or something else?)

My **.kitchen.yml**:

``` yaml
---
driver:
  name: digitalocean
  driver_config:
    ssh_key_ids: <%= ENV['DIGITALOCEAN_SSH_KEY_IDS'] %>
    ssh_key: <%= ENV['DIGITALOCEAN_SSH_KEY_PATH'] %>

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[dome::default]
    attributes:
```
